### PR TITLE
Run pre-commit

### PR DESCRIPTION
**Pull request by Zephyrkul**
Nothing more than just using `pre-commit run --all-files` so that (hopefully, if I did it right) your main branch will be passing checks again.

I looked over the changed files and it looks to all be the same beyond formatting and whitespace changes, but I haven't actually installed and ran this repo following these changes so your mileage may vary.

### CODE REVIEW

**Comment by Zephyrkul** [comment]
aight looks like more will be needed but it's a simple fix, it'll require a change to your pre-commit yaml though

**Comment by Zephyrkul** [comment]
All set, checks are green again.

I'll note that the issue with `black` and `click` is better resolved by bumping the version of black that your precommit uses, but this PR is focused solely on making your checks all green for your main branch.

**Comment by npc203** [comment]
Yup, sure, I'll merge after you bump the deps.

**Comment by Zephyrkul** [comment]
Should be all set.

**Comment by npc203** [comment]
Thanks for the PR!

**Pull request merged**
